version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/:/tmp/
    environment: 
      - GITLAB_SERVER=gitlabsvr:80
    ports:
      - 80:80
      - 443:443
    networks: 
      - glnetwork
    links: 
      - gitlabsvr
    depends_on: 
      - gitlabsvr
      
  gitlabsvr:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'  
    networks: 
      - glnetwork   

networks:
  glnetwork:
    driver: bridge